apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2022-03-03T22:51:33Z"
  name: api-key
  namespace: default
  resourceVersion: "818"
  uid: bce393d7-59e1-4fe5-9927-e61907459b5f
type: Opaque
